# Site settings
permalink: pretty
title: RiotGear2 - The NEW open source component library for RiotJS
description: The NEW open source component library for RiotJS.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://riotgear2.github.io" # the base hostname & protocol for your site
twitter_username: simplysuccess8
version: '3.6.0'

# Build settings
markdown: kramdown

# Navigation
navigation-getting-started:
- text: Install
  url: /getting-started/install/


navigation-community:
- text: Our Team Code
  url: /community/teamcode/

- text: Contributing
  url: /community/contributing/

- text: Forum
  url: /community/forum/


navigation-components:
- text: Accordion
  url: /components/accordion/
  class-name: newcomp

- text: Alerts
  url: /components/alerts/

- text: Bubble
  url: /components/bubble/

- text: Charts
  url: /components/charts/

- text: Code
  url: /components/code/

- text: Credit Card
  url: /components/creditcard/

- text: Date
  url: /components/date/

- text: Drawer
  url: /components/drawer/

- text: Google Analytics
  url: /components/ga/

- text: Iframify
  url: /components/iframify/

- text: Include
  url: /components/include/

- text: Map
  url: /components/map/

- text: Markdown
  url: /components/markdown/

- text: Modal
  url: /components/modal/

- text: Pagination
  url: /components/pagination/

- text: Phone Sim
  url: /components/phonesim/

- text: Placehold.it
  url: /components/placeholdit/

- text: Router
  url: /components/router/

- text: Select
  url: /components/select/

- text: Select (filter)
  url: /components/select-filter/

- text: Tabs
  url: /components/tabs/

- text: Tags
  url: /components/tags/

- text: Toasts
  url: /components/toasts/

- text: Toggle
  url: /components/toggle/

- text: Unsplash
  url: /components/unsplash/
